version: "3"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: list-of-houses
      POSTGRES_PASSWORD: list-of-houses
      POSTGRES_DB: list-of-houses_development
    ports:
    - "5432:5432"
    networks:
    - backend

networks:
  backend:
